# Generated by Django 5.0.7 on 2024-08-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('director', models.CharField(max_length=100)),
                ('review', models.CharField(max_length=100000000)),
                ('rating', models.CharField(max_length=23)),
                ('created_at', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=23)),
                ('genre', models.CharField(max_length=24)),
            ],
        ),
    ]
